# Generated by Django 6.0.3 on 2026-03-26 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Если отмечено, впечатление видно всем пользователям. Если нет — только вам.', verbose_name='Публичное'),
        ),
    ]
